paths:
  /clipping-set-text:
    post:
      security:
        - apikeyAuth: []
      parameters:
        - in: body
          name: body
          schema:
            type: object
      responses:
        200:
          description: Success
          schema:
            type: object

  /clipping-set-file:
    post:
      security:
        - apikeyAuth: []
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: upfile
          type: file
      responses:
        200:
          description: Success
          schema:
            type: object

  /clipping-get-text:
    get:
      security:
        - apikeyAuth: []
      responses:
        200:
          description: Success
          schema:
            type: object

  /clipping-get-file:
    get:
      security:
        - apikeyAuth: []
      responses:
        200:
          description: Success
          schema:
            type: file

  /clipping-check-file:
    post:
      security:
        - apikeyAuth: []
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: upfile
          type: file
      responses:
        200:
          description: Success
          schema:
            type: object